GTranslate Icon idea
isueit/iastate_theme pull request #36
Opened 2023-07-13 18:48 UTC by kennedy-rain

This makes gtranslate into an icon with a dropdown menu. This was made with Gtranslate put into 'Header Second' block under Block layout, but not sure if its the best placement for it

2023-07-18 19:12 UTC, Kristi-Elmore requested changes
The hover affect makes the logo pretty large and overlap the header border on the bottom.  I'd prefer not to have a zoom in on the hover.  Also - let's do the gold for the hover color instead of dark red.

I'm also seeing a problem with the social media red icons with this in the second header section - the social icons aren't showing for me when gtranslate is in the same section.  Not sure if order is important in the block layout screen or not.

2023-08-16 21:38 UTC, Kristi-Elmore commented
Only a couple changes I think @kennedy-rain 
Can we reduce the size of the icon to 1.45em (same size as the icons in the right hand footer block).
Can we reduce the spacing between Select Language and the arrow.

2023-08-17 14:36 UTC, kennedy-rain commented
@Kristi-Elmore okay I have made those changes 👍

2023-09-01 13:09 UTC, Kristi-Elmore commented
I've merged these changes into the white-bar branch.

2023-09-01 13:09 UTC, closed without merging